steps:
  # Docker 이미지 빌드
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/seoul-economy-platform:latest", "."]

  # Container Registry에 이미지 푸시
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/seoul-economy-platform:latest"]

  # Cloud Run에 배포
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "seoul-economy-platform",
        "--image",
        "gcr.io/$PROJECT_ID/seoul-economy-platform:latest",
        "--region",
        "asia-northeast3",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080",
        "--memory",
        "1Gi",
        "--cpu",
        "1",
        "--max-instances",
        "10",
        "--set-env-vars",
        "FLASK_ENV=production",
      ]

images:
  - "gcr.io/$PROJECT_ID/seoul-economy-platform:latest"

timeout: "1200s"
